[package]
name = "{{ crate_name }}"
authors = ["{{ author }} <{{ email }}>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs", "standalone"] }
react_plug = { git = "https://github.com/exa04/react_plug" }
crossbeam-channel = "0.5.13"
include_dir = "0.7.4"
serde = { version = "1.0.204", features = ["derive"] }
ts-rs = "9.0.1"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"

[workspace]
members = ["xtask"]